demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

from my_app import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('my_app/', include('my_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/my_app/urls.py
from django.urls import path
from my_app import views

app_name = 'my_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category,
         name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page,
         name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('like_category/', views.like_category, name='like_category'),
    path('suggest/', views.suggest_category, name='suggest_category'),
]

demo/my_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

demo/my_app/forms.py
from django import forms
from my_app.models import Page, Category
from django.contrib.auth.models import User
from my_app.models import UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                           help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model.
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,
                            help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH,
                         help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        # fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

demo/my_app/views.py
from django.shortcuts import render
from my_app.models import Category
from my_app.models import Page
from my_app.forms import CategoryForm, PageForm
from django.shortcuts import redirect
from django.urls import reverse
from my_app.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    # request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'my_app/index.html', context_dict)


def about(request):
    # if request.session.test_cookie_worked():
    #    print("TEST COOKIE WORKED!")
    #    request.session.delete_test_cookie()
    context_dict = {}
    context_dict['aboutmessage'] = 'My_app says here is the about page.'
    return render(request, 'my_app/about.html', context_dict)


def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}

    # try/ except语句用来检测try语句块中的错误，从而让except语句捕获异常信息并处理。
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

    # Go render the response and return it to the client.
    return render(request, 'my_app/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            # Now that the category is saved
            # We could give a confirmation message
            # But since the most recent category added is on the index page
            # Then we can direct the user back to the index page.
            return index(request)
        else:
            # The supplied form contained errors
            # just print them to the terminal.
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'my_app/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('my_app: show_category',
                                        kwargs={'category_name_slug':
                                                category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'my_app/add_page.html', context_dict)


def register(request):
    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else? Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request, 'my_app/register.html', {'user_form': user_form,
                                                    'profile_form': profile_form,
                                                    'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('my_app:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your My_app account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details:{0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'my_app/login.html')


@login_required
def restricted(request):
    context_dict = {}
    context_dict['restrictedmessage'] = "Since you're logged in, you can see this text!"
    return render(request, 'my_app/restricted.html', context_dict)


# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('my_app:index'))


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
    likes = 0
    if cat_id:

demo/templates/my_app/about.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About My_app
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">My_app About Page</h1>
        </div>
    </div>

    <div>
        <strong>{{ aboutmessage }}</strong>
    </div>

    <button class="btn btn-primary" onclick="alert('You clicked the button using inline JavaScript.');">
        Click me - I run on vanilla JavaScript!
    </button>

    <br />
    <br />

    <button class="btn btn-primary" id="about-btn">
        Click me - I'm using JQuery!
    </button>

    <p>This is some text for the JQuery example.</p>

    <div id="msg">Hello! I'm a further example for JQuery testing.</div>
{% endblock %}

demo/templates/my_app/add_category.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Category</h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <form role="form" id="category_form" method="post" action="{% url 'my_app:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                <div class="p-2"></div>
                {% endfor %}
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Category
                </button>
            </form>
        </div>
    </div>
{% endblock %}

demo/templates/my_app/add_page.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    {% if category %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add Page to {{ category.name }}</h1>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <form role="form" id="page_form" method="post" action="{% url 'my_app:add_page' category.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                <div class="p-2"></div>
                {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Page
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
    {% else %}
    <div class="jumbotron p-4">
        <div class="container">
            <h2 class="jumbotron-heading">Add a Page</h2>
        </div>
    </div>
    <div>
        The specified category does not exist.
    </div>
    {% endif %}
{% endblock %}

demo/templates/my_app/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_app_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            my_app -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                    <li><a href="{% url 'my_app:add_category' %}">Add New Category</a> </li>
                    <li><a href="{% url 'my_app:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'my_app:logout' %}">Logout</a></li>
                {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                    <li><a href="{% url 'my_app:register' %}">Sign Up</a> </li>
                    <li><a href="{% url 'my_app:login' %}">Login</a> </li>
                {% endif %}
                <!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'my_app:about' %}">About</a> </li>
                <li><a href="{% url 'my_app:index' %}">Index</a> </li>
            </ul>
        </div>
    </body>
</html>

demo/templates/my_app/base.html
<!doctype html>
{% load staticfiles %}
{%load my_app_template_tags%}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
      My_app - {% block title_block %} How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
  <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
        <a class="navbar-brand p-2" href="{% url 'my_app:index' %}">My_app</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" href="{% url 'my_app:index' %}">Home</a></li>
              <li class="nav-item "><a class="nav-link" href="{% url 'my_app:about' %}">About</a></li>
              {% if user.is_authenticated %}
                <li class="nav-item "><a class="nav-link" href="{% url 'my_app:restricted' %}">Restricted</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my_app:add_category' %}">Add Category</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my_app:logout' %}?next=/my_app/">Logout</a></li>
              {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'my_app:register' %}">Register Here</a></li>
                <li class="nav-item "><a class="nav-link" href="{% url 'my_app:login' %}">Login</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="w-75 ml-3">
          <li class="nav-item">Type to find a category</li>
          <input type="text"
                 id="suggestion"
                 class="search-query form-control"
                 name="suggestion"
                 value=""
                 placeholder="Search..." />
        </div>
        <div class="sidebar-sticky" id="categories-listing">
          {% block sidebar_block %}
            {% get_category_list category %}
          {% endblock %}
        </div>
      </nav>

      <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
        {% block body_block %}
        {% endblock %}
        <!-- FOOTER -->
        <footer>
          <p class="float-right"><a href="#">Back to top</a></p>
          <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        </footer>
      </main>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'js/my_app-jquery.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'js/my_app-ajax.js' %}" crossorigin="anonymous"></script>
  <script>
        window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js">
  </script>
  <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js">
  </script>
  </body>
</html>

demo/templates/my_app/categories.html
<ul class="navflex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'my_app:show_category' c.slug %}"><span data-feather="github"></span>{{ c.name }}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

demo/templates/my_app/category.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <div class="jumbotron p-4">
            <div class="container">
                <h1 class="jumbotron-heading">{{ category.name }}</h1>
            </div>

            <div>
                <strong id="like_count">{{ category.likes }}</strong> likes
                &nbsp;&nbsp;
                {% if user.is_authenticated %}
                    <button id="like_btn"
                            data-categoryid="{{ category.id }}"
                            class="btn btn-primary btn-sm"
                            type="button">
                    <span data-feather="thumbs-up"></span>
                        Like Category
                    </button>
                {% endif %}
            </div>
        </div>

        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a> </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'my_app:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %}
        The specified category does not exit!
    {% endif %}
{% endblock %}

demo/templates/my_app/index.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">my_app says a story of five angles</h1>
            <div>
            <h2 class="h2">
            {% if user.is_authenticated %}
                howdy {{ user.username }}!
            {% else %}
                hey there partner!
            {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-6">
                    <div class="card-body">
                        <h2>Most Liked Categories</h2>
                        <p class="card-text">
                        {% if categories %}
                        <ul class="list-group">
                            {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'my_app:show_category' category.slug %}">
                                    {{ category.name }}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            <strong>There are no categories present.</strong>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-6">
                    <div class="card-body">
                        <h2>Most Views Pages</h2>
                        <p class="card-text">
                        {% if pages %}
                        <ul class="list-group">
                            {% for page in pages %}
                            <li class="list-group-item">
                                <a href="{{ page.url }}">{{ page.title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                            <strong>There are no pages present.</strong>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br />  <!--实现空行-->

    <div>
        <img src="{% static 'images/hardman.jpg' %}" alt="Picture of hardman" />

        <img src="{{ MEDIA_URL}}cat.jpg" alt="Picture of cat" />
    </div>
{% endblock %}

demo/templates/my_app/login.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css"
          rel="stylesheet">
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Login to My_app</h1>
        </div>
    </div>

<!--
    <div class="container">
        <form id="login_form" method="post" action="{% url 'my_app:login' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
            <input type="submit" value="submit" />
        </form>
    </div>
-->

    <div class="container">
    <form class="form-signin" role="form" method="post" action=".">
        {% csrf_token %}
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="username" id="id_username" class="form-control"
               placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" class="form-control"
               placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit"
                value="Submit">Sign in</button>
    </form>
    </div>
{% endblock %}

demo/templates/my_app/register.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Register for My_app</h1>
        </div>
    </div>

    <div class="container">
        {% if registered %}
            My_app says: <strong>thank you for registering!</strong>
            <a href="{% url 'my_app:index' %}">Return to the homepage.</a><br />
        {% else %}
            My_app says: <strong>register here!</strong><br />
            <form id="user_form" method="post" action="{% url 'my_app:register' %}"
                  enctype="multipart/form-data">

                {% csrf_token %}

                <!-- Display each form -->
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <!-- Provide a button to click to submit the form. -->
                <button class="btn btn-primary" type="submit" name="submit">
                    Register
                </button>
            </form>
        {% endif %}
    </div>
{% endblock %}

demo/templates/my_app/restricted.html
{% extends 'my_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page of My_app
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">My_app Restricted Page</h1>
        </div>
    </div>

    <div>
        <strong>{{ restrictedmessage }}</strong>
    </div>
{% endblock %}